[package]
name = "spine-rbx/service"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
object = "spine-rbx/object@*"
net = "spine-rbx/net@*"
util = "spine-rbx/util@*"
promise = "spine-rbx/promise@*"